### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by noahhefner** [noahhefner/tkinter-multi-page#1]
- [ ] Set window size
- [ ] Set window title
- [ ] Set default page frame
- [ ] Add drive mapper and diff highlight as pages
